version: "3"
services:
    back:
        build: ./backend
        container_name: back
        ports:
        - "3000:3000"
        networks:
            - apinetwork
    web:
        build: ./frontend/frontend
        container_name: web
        ports:
        - "80:80"
        networks:
            - apinetwork
networks:
        apinetwork:
            driver: bridge    